### ISSUE TITLE
`origin` wildcard does not support underscores

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#616]
**Current Behavior**
To define inputs for the workflow, we create a `builds.yaml` file that contains a list of named inputs in a format like this:

```
inputs:
  - name: input1
    metadata: data/example_metadata.tsv
    sequences: data/example_sequences.fasta.gz
```

The `name` field of each input is used in the Snakemake workflow in the `origin` wildcard. This wildcard includes a leading underscore (by design) such that the example input about would produce files like `results/filtered_input1.fasta` where the wildcard is `_input1`.

[The constraints on the format of this "origin" wildcard](https://github.com/nextstrain/ncov/blob/3072c0079a3687ab11eabef8a496dfadfb95cf1c/Snakefile#L94) do not allow for underscores in the input names. For example, the following reasonable input definition:

```
inputs:
  - name: getting_started
    metadata: data/example_metadata.tsv
    sequences: data/example_sequences.fasta.gz
```

produces the following unintelligible error:

```
MissingInputException in line 363 of /Users/jlhudd/projects/nextstrain/ncov/workflow/snakemake_rules/main_workflow.smk:
Missing input files for rule index_sequences:
results/filtered_getting_started.fasta
```

**Expected behavior**

Users should be able to define whatever names they like for their input data and have these names be processed by the workflow without any errors.

**How to reproduce**

Copy and paste the example `inputs` entry above into `my_profiles/getting_started/builds.yaml`.

**Possible solution**

Instead of placing the `origin` wildcard inside the name of each associated file, use the `origin` wildcard as a subdirectory in `results/` (or even `data/` might make more sense). Additionally, drop support for the deprecated `config["sequences"]` and `config["metadata"]` interface and require users to define at least one entry in the config's `inputs`.

These changes will allow us to know that we always have an "origin" defined (instead of supporting the optional empty origin) and they will also make the wildcard's values more flexible because they can contain any reasonable values that a directory name can have. This approach will also have the benefit of cleanly organizing files into subdirectories by input, allowing users to discover and inspect these files more easily.
