### ISSUE TITLE
Error with snakemake workflow when using min_date and max_date

### ISSUE THREAD

**Issue by garfinjm** [nextstrain/ncov#644]
**Current Behavior**
min_date and max_date subsampling parameters defined in builds yaml aren't generating a valid augur filter command in the snakemake workflow.

My builds.yaml
```
inputs:
  - name: gisaid
    metadata: data/metadata_2021-05-11_09-01.tsv
    sequences: data/sequences_2021-05-11_06-20.fasta

builds:
  MNextstrain:
    subsampling_scheme: mn_twomonth
    region: North America
    country: USA
    division: Minnesota


subsampling:
  mn_twomonth:
    # This is based on the CDC/Spheres contextual subsampling scheme, modified to select for recent samples
    mn-recent:
      group_by: "year"
      max_sequences: 100000
      min_date: "2021-03-20"
      query: --query "(country == 'USA' & division == '{division}')"
    mn-historic:
      group_by: "year month"
      seq_per_group: 100
      max_date: "2021-03-19"
      query: --query "(country == 'USA' & division == '{division}')"
    usa-context:
      group_by: "year month"
      max_sequences: 500
      query: --query "(country == 'USA' & division != '{division}')"
      priorities:
        type: proximity
        focus: mn-recent
    global-context:
      group_by: "region year month"
      max_sequences: 500
      query: --query "(country != 'USA')"
      priorities:
        type: proximity
        focus: mn-recent

files:
  auspice_config: "my_profiles/MNextstrain/MNextstrain_config.json"
  description: "my_profiles/MNextstrain/MNextstrain_description.md"

```

The errors I get are below, it looks like `--max-date` and `--min-date` are missing from the `augur filter` command, so the values of those params are being interpreted as an additional exclude list:
```
[Thu May 20 13:43:30 2021]
Job 16: 
        Subsample all sequences by 'mn-historic' scheme for build 'MNextstrain' with the following parameters:

         - group by: --group-by year month
         - sequences per group: --sequences-per-group 100
         - subsample max sequences: 
         - min-date: 
         - max-date: 2021-03-19
         - 
         - exclude: 
         - include: 
         - query: --query "(country == 'USA' & division == 'Minnesota')"
         - priority: 
        


        augur filter             --sequences results/filtered_gisaid.fasta             --metadata results/sanitized_metadata_gisaid.tsv             --sequence-index results/combined_sequence_index.tsv             --include defaults/include.txt             --exclude defaults/exclude.txt                          2021-03-19                                       --query "(country == 'USA' & division == 'Minnesota')"                                       --group-by year month             --sequences-per-group 100                                       --output results/MNextstrain/sample-mn-historic.fasta             --output-strains results/MNextstrain/sample-mn-historic.txt 2>&1 | tee logs/subsample_MNextstrain_mn-historic.txt
        

[Thu May 20 13:43:30 2021]
Job 15: 
        Subsample all sequences by 'mn-recent' scheme for build 'MNextstrain' with the following parameters:

         - group by: --group-by year
         - sequences per group: 
         - subsample max sequences: --subsample-max-sequences 100000
         - min-date: 2021-03-20
         - max-date: 
         - 
         - exclude: 
         - include: 
         - query: --query "(country == 'USA' & division == 'Minnesota')"
         - priority: 
        


        augur filter             --sequences results/filtered_gisaid.fasta             --metadata results/sanitized_metadata_gisaid.tsv             --sequence-index results/combined_sequence_index.tsv             --include defaults/include.txt             --exclude defaults/exclude.txt             2021-03-20                                                    --query "(country == 'USA' & division == 'Minnesota')"                                       --group-by year                          --subsample-max-sequences 100000                          --output results/MNextstrain/sample-mn-recent.fasta             --output-strains results/MNextstrain/sample-mn-recent.txt 2>&1 | tee logs/subsample_MNextstrain_mn-recent.txt
        
[Thu May 20 13:44:19 2021]
Error in rule subsample:
    jobid: 15
    output: results/MNextstrain/sample-mn-recent.fasta, results/MNextstrain/sample-mn-recent.txt
    log: logs/subsample_MNextstrain_mn-recent.txt (check log file(s) for error message)
    shell:
        
        augur filter             --sequences results/filtered_gisaid.fasta             --metadata results/sanitized_metadata_gisaid.tsv             --sequence-index results/combined_sequence_index.tsv             --include defaults/include.txt             --exclude defaults/exclude.txt             2021-03-20                                                    --query "(country == 'USA' & division == 'Minnesota')"                                       --group-by year                          --subsample-max-sequences 100000                          --output results/MNextstrain/sample-mn-recent.fasta             --output-strains results/MNextstrain/sample-mn-recent.txt 2>&1 | tee logs/subsample_MNextstrain_mn-recent.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile logs/subsample_MNextstrain_mn-recent.txt:
ERROR: Could not open file of excluded strains '['defaults/exclude.txt', '2021-03-20']'


[Thu May 20 13:44:19 2021]
Error in rule subsample:
    jobid: 16
    output: results/MNextstrain/sample-mn-historic.fasta, results/MNextstrain/sample-mn-historic.txt
    log: logs/subsample_MNextstrain_mn-historic.txt (check log file(s) for error message)
    shell:
        
        augur filter             --sequences results/filtered_gisaid.fasta             --metadata results/sanitized_metadata_gisaid.tsv             --sequence-index results/combined_sequence_index.tsv             --include defaults/include.txt             --exclude defaults/exclude.txt                          2021-03-19                                       --query "(country == 'USA' & division == 'Minnesota')"                                       --group-by year month             --sequences-per-group 100                                       --output results/MNextstrain/sample-mn-historic.fasta             --output-strains results/MNextstrain/sample-mn-historic.txt 2>&1 | tee logs/subsample_MNextstrain_mn-historic.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile logs/subsample_MNextstrain_mn-historic.txt:
ERROR: Could not open file of excluded strains '['defaults/exclude.txt', '2021-03-19']'


Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /panfs/roc/groups/7/mdh/shared/sc2/nextstrain/nextstrain_official/ncov/.snakemake/log/2021-05-20T134329.683768.snakemake.log


```

**Expected behavior**
`min_date` and `max_date` are incorporated into the `augur filter` commmand preceeded by `--min-date` and `--max-date`

**How to reproduce**
See builds.yaml above. 

**Your environment: if running Nextstrain locally**
 - Operating system: centos-release-7-9.2009.1.el7.centos.x86_64
 - Browser: NA
 - Version (e.g. `auspice 2.7.0`): 
nextstrain.cli 3.0.3
augur 12.0.0
conda environment and ncov repository both updated 5/20/2021

**Additional context**
It's definitly possible I just have something setup wrong. Any help is appreciated and thanks for making such a great tool!

Jake

**Comment by huddlej** [comment]
Hi @garfinjm! This is definitely an inconsistency in our workflow parameters where most of the workflow expects specific dates for `min_date` and `max_date` while [the subsampling parameters](https://nextstrain.github.io/ncov/configuration.html#subsampling) expect a full augur filter flag. In your builds, this means the min and max dates have to be defined like:

```yaml
subsampling:
  mn_twomonth:
    # This is based on the CDC/Spheres contextual subsampling scheme, modified to select for recent samples
    mn-recent:
      group_by: "year"
      max_sequences: 100000
      min_date: "--min-date 2021-03-20"
      query: --query "(country == 'USA' & division == '{division}')"
    mn-historic:
      group_by: "year month"
      seq_per_group: 100
      max_date: "--max-date 2021-03-19"
      query: --query "(country == 'USA' & division == '{division}')"
[...snip...]
```

We need to change this behavior so the subsampling configuration behaves like the rest of the configuration, but for the short term you can update your builds to use the style above and it should work. Sorry to have made this more confusing than it needed to be!
