### ISSUE TITLE
Pipeline on Spikes genes

### ISSUE THREAD

**Issue by davidvilanova** [nextstrain/ncov#695]
Hi,
I was trying to run the nextstrain to align and generate a tree for a list of fasta nucleotide sequences coming from a targeted sequence of the S gene.

I have update the build.yaml to lower input sequence size filter as follows:

`filter:  min_length: 1000`

The run fails with the following output:

![image](https://user-images.githubusercontent.com/11404840/127331847-8274a7db-0e34-4d0e-9d2b-ce2ecabef05c.png)

Is it possible to run the pipeline with only the S gene ?? Am i missing something ?

Thanks

**Comment by emmahodcroft** [comment]
Hi David! Thanks for reaching out. From what it's showing here, it seems like it's not able to connect your metadata file and your sequence file - possibly because the names of the sequences do not exactly match between the two. For example, maybe one has an `hCoV-19` start, or one might have `_` while the other uses `-` or `/`?  This would be the first thing to check - let us know if this helps the issue!

**Comment by davidvilanova** [comment]
Thanks @emmahodcroft for the hint. I have actually corrected some problems with both fasta and metadata to match ids.

So far they are the same. I have double checked running diff on both metadata and sequence file

![image](https://user-images.githubusercontent.com/11404840/127372876-25fc51e5-6874-4246-af39-9e0afdebdd2d.png)


So far getting a similar error:
![image](https://user-images.githubusercontent.com/11404840/127372389-295e06a2-2ef5-494e-a634-8c76bb0d396f.png)

**Comment by jameshadfield** [comment]
@davidvilanova what kind of (sample) date informationis in the metadata? Ideally each sample would have an exact sampling date (written as YYYY-MM-DD). Looking at the command, it is being run with `--exclude-ambiguous-dates-by any` which results in everything (n=63) being dropped. 

If you want to include ambiguous dates, then you can modify the `builds.yaml` to include
```yaml
filter:
    Andorra-data:
         exclude_ambiguous_dates_by: month # or year, as required
```

**Comment by davidvilanova** [comment]
Hi @jameshadfield 
I have used the default parameters.yaml which incoroporated the `--exclude-ambiguous-dates-by any`
 Ideally i would like to dsicard this filter. The metada is generated through another script where i check already for the date.
 
 Here is the header of my metadafile.  Seems ok ?


```
strain  virus   gisaid_epi_isl  genbank_accession       date    region  country division        location        region_exposure country
_exposure       division_exposure       segment length  host    age     sex     originating_lab authors url     title   date_submitted
ANDORRA/AND-220_5164_COV-A6/2021        Sars-Cov-2                      2020/07/20      EUROPE  ANDORRA ANDORRA ANDORRA ANDORRA       surface glycoprotein (S) 2261    Homo sapiens                    LNE
ANDORRA/AND-220_6062_COV-A6/2021        Sars-Cov-2                      2020/07/20      EUROPE  ANDORRA ANDORRA ANDORRA ANDORRA       surface glycoprotein (S) 2262    Homo sapiens                    LNE
ANDORRA/AND-220_6742_COV-A6/2021        Sars-Cov-2                      2020/07/20      EUROPE  ANDORRA ANDORRA ANDORRA ANDORRA       surface glycoprotein (S) 2262    Homo sapiens                    LNE

I have tried your suggestion with the date, although it looks good to me. Still fails...
<img width="1436" alt="Captura de pantalla 2021-07-28 a las 22 33 03" src="https://user-images.githubusercontent.com/11404840/127392298-681dafb6-d590-4fa2-965b-dd0df6aa878a.png">

```

**Comment by davidvilanova** [comment]
Sorry the image didn´t upload correctly
<img width="1436" alt="Captura de pantalla 2021-07-28 a las 22 33 03" src="https://user-images.githubusercontent.com/11404840/127392488-26446629-3e34-47aa-badc-2de52103f059.png">

**Comment by emmahodcroft** [comment]
Hi David, looks like you do have dates, but the format needs to be updated.
Try 2020-07-20 with `-` instead of the `/`, I really hope this might work!

**Comment by emmahodcroft** [comment]
Ah, I've just realised this seems to be `date_submitted` rather than
`date`. To do a time resolved analysis you'll need a `date` column with the
Sampling date rather than the collection date. Do you have this information?

**Comment by jameshadfield** [comment]
> Here is the header of my metadafile. Seems ok ?

The dates needs to be changed from (e.g.) `2020/07/20` to `2020-07-20`. With this change, I don't think any further changes to `exclude_ambiguous_dates_by` will be necessary.

**Comment by davidvilanova** [comment]
Great, that fixed the date problem.

I still have a filter that drops out all the sequences?
![image](https://user-images.githubusercontent.com/11404840/127453524-7de3ea9f-3b85-4d2b-9e8a-f161e2495b00.png)


```
builds.yaml:
# Define input files.
inputs:
  - name: Andorra-data
    metadata: data/metadata_Andorra.tsv
    sequences: data/spikes_clean.fa
builds:
  ANDORRA:
    subsampling_scheme: country 
    region: EUROPE
    country: ANDORRA
```

I´m using the defaults parameter.yaml.

**Comment by davidvilanova** [comment]
Hi,
I´ve update my builds.yaml as follow based on the example from switzerland. It went through pretty good until it creates the tree. 
Not sure what the problem is there with the Wuhan root. This sequence is part of the reference , not my dataset. What´s wrong ?

```
inputs:
  - name: Andorra-data
    metadata: data/metadata_Andorra.tsv
    sequences: data/spikes_clean.fa

builds:
  andorra:
    subsampling_scheme: andorra 
    region: EUROPE
    country: ANDORRA
    title: "SARS-CoV-2 Sequences in Andorra"

subsampling:
  andorra:
    country:
      group_by: "division year month"
      max_sequences: 1500
      exclude: "--exclude-where 'country!={country}'"
    # Contextual samples from country's region
    region:
      group_by: "country year month"
      seq_per_group: 20
      exclude: "--exclude-where 'country={country}' 'region!={region}'"
      priorities:
        type: "proximity"
        focus: "country"
    # Contextual samples from the rest of the world,
    # excluding the current region to avoid resampling.
    global:
      group_by: "country year month"
      seq_per_group: 10
      exclude: "--exclude-where 'region={region}'"
      priorities:
        type: "proximity"
        focus: "country"

files:
  auspice_config: "my_profiles/andorra/my_auspice_config.json"
  description: "my_profiles/andorra//my_description.md"

  # Define genes to translate during alignment by nextalign.
genes: ["S"]

# Filter settings
filter:
  # Require nearly full-length genomes.
  min_length: 1000
  exclude_ambiguous_dates_by: month 


```


![image](https://user-images.githubusercontent.com/11404840/127481485-631f53e0-563a-4077-b215-7625bfa86bde.png)

**Comment by davidvilanova** [comment]
Hi, 
I have fixed this by adding the reference sequence to my dataset.

Now there is a new problem (described here https://github.com/nextstrain/augur/issues/575 ). See shot

![image](https://user-images.githubusercontent.com/11404840/127541100-ca67ec39-3c8d-4573-9b9a-a9d4c0546ce8.png)

I have added all the columns if the metadata with the coutry name for `country division location region_exposure country_exposure division_exposure segment` but it does not work. Can i disable this feature ?? The link to the bug to disable this feature is not working.

The metadata now looks this way:
```
strain  virus   gisaid_epi_isl  genbank_accession       date    region  country division        location        region_exposure country_exposure       division_exposure       segment length  host    age     sex     originating_lab authors url     title   date_submitted
Wuhan/Hu-1/2019 Sars-Cov-2      ?       ?       2020-07-20      EUROPE  ANDORRA ANDORRA ANDORRA ANDORRA ANDORRA ANDORRA surface glycoprotein (S)       2261    Homo sapiens    ?       ?       LNE     ?       ?       ?       2020-07-22
ANDORRA/AND-220_5164_COV-A6/2021        Sars-Cov-2      ?       ?       2020-07-20      EUROPE  ANDORRA ANDORRA ANDORRA ANDORRA ANDORRAANDORRA surface glycoprotein (S)        2261    Homo sapiens    ?       ?       LNE     ?       ?       ?       2020-07-22
ANDORRA/AND-220_6062_COV-A6/2021        Sars-Cov-2      ?       ?       2020-07-20      EUROPE  ANDORRA ANDORRA ANDORRA ANDORRA ANDORRAANDORRA surface glycoprotein (S)        2262    Homo sapiens    ?       ?       LNE     ?       ?       ?       2020-07-22
```


Thanks

**Comment by davidvilanova** [comment]
Ok I have fixed the problem by commenting out the line 1158 in main_workflow.smk

`        #rules.traits.output.node_data,
`
Eveything ok.

So after going through all the steps, i have identified 2 main points that were not addressed :
- Need to add the reference strain to my dataset
- Need to comment out the line above

Hope helps others,

**Comment by davidvilanova** [comment]
One more quick comment. All variants were annotated as belonging to the CLADE 19A which is not correct as i expect other clades to be present ??

**Comment by davidvilanova** [comment]
HI @jameshadfield . 
Sorry to bother with this issue. Al the pipelines seems to run properly but all clades are assigned to CLADE 19A. Looks to me the alignments could be the problem ?

**Comment by jameshadfield** [comment]
Hi @davidvilanova - well done on working through the pipeline issues.

The `traits` problem can be solved by specifying what metadata columns, if any, you wish to run DTA on via your `builds.yaml` config. Here's what the default looks like:

```yaml
traits:
  default:
    sampling_bias_correction: 2.5
    columns: ["country_exposure"]
```
