### ISSUE TITLE
Exit with an error when user requests an undefined subsampling scheme

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#699]
**Current Behavior**
If a user requests an undefined subsampling scheme (that sounds logical to them as a scheme that _should_ exist like "state" or "county"), [the current workflow will print a warning and continue using all available data](https://github.com/nextstrain/ncov/blob/04f20227304d790a75a874b837a0d96446104afe/workflow/snakemake_rules/main_workflow.smk#L224-L230). Depending on the input data, this could cause the workflow to run for a very long time before the user catches the issue.

**Expected behavior**
The workflow should use all available data only when the subsampling scheme is set to "all" or is undefined. When an explicit subsampling scheme is requested by the user, the workflow should print a helpful error and exit.

**How to reproduce**

Create a `builds.yaml` file with the following contents:

```yaml
# Define inputs
inputs:
  - name: open
    metadata: s3://nextstrain-data/files/ncov/open/metadata.tsv.gz
    filtered: s3://nextstrain-data/files/ncov/open/filtered.fasta.xz

# Define builds.
builds:
  random:
    subsampling_scheme: county
```

Dry-run a build with this file (notice the warning):

```bash
snakemake -np --configfile builds.yaml
```

**Possible solution**
Check for whether subsampling scheme is `None` or an empty string instead of checking whether it's in the list of defined schemes and then set it to `all`. Otherwise, if it's not in the list of defined schemes print an error to standard error and exit with a nonzero code.

**Additional context**
Thank you to @BryanTegomoh for reporting this issue.
