### ISSUE TITLE
Move index/filter after subsampling

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#810]
**Context**
Indexing and filtering are slow and unnecessary for most of the workflow to run.

**Description**
We should move the index/filter steps after the subsampling step so logic order will be:

 - subsample
 - align
 - mask
 - filter
 - tree

**Comment by jameshadfield** [comment]
Agreed. To do this for subsampling should we avoid providing sequences to the `augur filter` steps? This will limit the available filtering options, but given the rich metadata we have I think this is acceptable.

**Comment by huddlej** [comment]
I'll make an attempt at this now.

**Comment by huddlej** [comment]
Some notes as I work on this:

1. Moving filter later in the workflow means we can no longer support origin-specific filter configuration parameters like this one from the `example_multiple_inputs` build:

```yaml
# STAGE 1: Input-specific filtering parameters
filter:
  aus:
    min_length: 5000 # Allow shorter genomes. Parameter used to filter alignment.
    skip_diagnostics: True # skip diagnostics (which can remove genomes) for this input
```

These would need to be converted to top-level filter parameters like:

```
# STAGE 1: Input-specific filtering parameters
filter:
  min_length: 5000
  skip_diagnostics: True
```

Actually, the diagnostic rule doesn’t make sense at the beginning of the workflow anymore since it analyzes each input “origin” and we don’t have a mapping of origins to build names after subsampling. It would make more sense to do diagnostics after subsampling and alignment (with Nextclade), before filtering.

2. We need the sequence index at the beginning of the workflow, still, because priorities use the sequence index and the proximity calculation need to extract subsampled sequences for the focal set.

The priorities script only seems to use the number of Ns in each sequence for its calculations, so maybe we could pull this information from somewhere else (e.g., seqtk comp, etc.).

We could also extract subsampled sequences with samtools, seqkit, faSomeRecords, etc. depending on compatibility of those tools with our sequence compression format.

Fortunately, we only need to build the sequence index in the case with priorities. Here is the DAG without priorities (assuming unaligned input):

![image](https://user-images.githubusercontent.com/85372/145492332-11f6ca53-73c6-49f2-9d17-61a3f45e5c2f.png)

Here is the DAG with priorities (where we need to index sequences and extract sequences for focal subsampled set):

![image](https://user-images.githubusercontent.com/85372/145492272-e083f710-fe11-4480-92d0-2816a8982b00.png)
