### ISSUE TITLE
v10 - Failure to combine multiple input files when "aligned" sequence files are specified

### ISSUE THREAD

**Issue by jacaravas** [nextstrain/ncov#838]
When multiple sequence files with the "aligned" entry point are specified in the build file I get the following error:

```
Config file defaults/parameters.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
WorkflowError in line 212 of /ncov/workflow/snakemake_rules/main_workflow.smk:
Function did not return str or list of str.
```

If "aligned" is switched to "sequences", the build runs correctly.

Envrironment:
v10 environment installed 01-11-2022 using the recommended install procedure

Command:
`snakemake --profile buildDir --jobs 1`

Build file (I hacked this together for this issue.  Hopefully it is mostly right)
```yaml
files:
  auspice_config: "buildDir/auspice_config.json"

genes: ["ORF1a", "ORF1b", "S", "ORF3a", "M", "N"]

inputs:
  - name: northamerica
    aligned: https://data.nextstrain.org/files/ncov/open/north-america/aligned.fasta.xz
    metadata: https://data.nextstrain.org/files/ncov/open/north-america/metadata.tsv.xz
  - name: globaldata
    aligned: https://data.nextstrain.org/files/ncov/open/global/aligned.fasta.xz
    metadata: https://data.nextstrain.org/files/ncov/open/global/metadata.tsv.xz
  - name: references
    sequences: data/references_sequences.fasta
    metadata: data/references_metadata.tsv
    
builds:
  basic:
    subsampling_scheme: basic
    region: North America
    country: USA

subsampling:
  basic:
    local-focus:
      group_by: "year month"
      max_sequences: 500
      query: --query "(northamerica == 'yes') & (country == '{country}')"
    global-context:
      group_by: "region year month"
      max_sequences: 200
      query: --query "(globaldata == 'yes') &(region != '{region}')"
```
