### ISSUE TITLE
subsampling_scheme min-date and max-date don't work

### ISSUE THREAD

**Issue by abattenhouse** [nextstrain/ncov#887]
Supplying a min-date or max-date subsampling_scheme value results in an error. I ran into this when attempting to subsample with a min-date using Nextstrain code downloaded 2/21/2022.

I fixed the problem in my local code and have created a pull request with my 4-line proposed solution. See:
"Fix subsampling_scheme min-date and max-date parameters bug. #886"

**Comment by jameshadfield** [comment]
@abattenhouse can you try using the following format in the YAML

```yaml
# Subsampling parameters
subsampling:
  your_scheme_name:
    your_sample_name:
      min_date: "--min-date 2000-01-01"
      max_date: "--max-date 2002-01-01"
```

Similar issue: https://github.com/nextstrain/ncov/issues/644#issuecomment-849946060
Reference docs: https://github.com/nextstrain/ncov/blob/master/docs/src/reference/configuration.md#min_date-2
